# Force dep to vendor dependencies needed for codegen
# For now, we must specify all subpackages required due to a limitation of dep
# See https://github.com/golang/dep/issues/1306
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.2.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.1"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "v1.7.2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[[constraint]]
  name = "github.com/containership/csctl"
  revision = "f38128550600f3d718d0f57631b5743abdd0cfb9"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "github.com/containership/cluster-manager"
  version = "v4.0.1"

[prune]
  go-tests = true
  # Note that we can't do this due to the code generator packages required; see above
  #unused-packages = true
